"""Disk cache in front of the content backend: same (doc_type, pitch_meta)
always maps to the same cache key, so re-running `generate` with the same
seed reuses previously generated bytes instead of re-invoking `claude -p`
(or the stub backend) and instead of re-rendering. See Ticket 0008's
determinism acceptance criterion.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path

from mock_gmail_api.docgen import render_docx, render_pdf, render_xlsx
from mock_gmail_api.docgen.catalog import DocType
from mock_gmail_api.docgen.content import ContentBackend, get_backend
from mock_gmail_api.models import PitchMeta

CACHE_DIR_ENV_VAR = "MOCK_GMAIL_DOCGEN_CACHE_DIR"
DEFAULT_CACHE_DIR = Path(".docgen_cache")

_RENDERERS = {
    "pitch_deck": render_pdf.render,
    "one_pager": render_docx.render,
    "cap_table": render_xlsx.render,
}


def cache_key(doc_type: DocType, meta: PitchMeta) -> str:
    payload = json.dumps(
        {
            "doc_type": doc_type.key,
            "company_name": meta.company_name,
            "sector": meta.sector,
            "stage": meta.stage,
            "ask": meta.ask,
        },
        sort_keys=True,
    )
    return hashlib.sha256(payload.encode()).hexdigest()


def default_cache_dir() -> Path:
    return Path(os.environ.get(CACHE_DIR_ENV_VAR, str(DEFAULT_CACHE_DIR)))


@dataclass(frozen=True, slots=True)
class DocumentCache:
    cache_dir: Path
    backend: ContentBackend

    def get_or_generate(self, doc_type: DocType, meta: PitchMeta) -> tuple[str, bytes]:
        """Returns (content_ref, rendered_bytes). content_ref is the
        filename to store on the Attachment row and to look the bytes back
        up by later (see server.py's get_attachment)."""
        key = cache_key(doc_type, meta)
        content_ref = f"{key}.{doc_type.extension}"
        path = self.cache_dir / content_ref
        if path.exists():
            return content_ref, path.read_bytes()

        text = self.backend.generate(doc_type, meta)
        title = f"{meta.company_name} — {doc_type.key.replace('_', ' ').title()}"
        data = _RENDERERS[doc_type.key](title, text)

        self.cache_dir.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return content_ref, data

    def read(self, content_ref: str) -> bytes:
        return (self.cache_dir / content_ref).read_bytes()


def default_cache(backend_name: str | None = None) -> DocumentCache:
    return DocumentCache(cache_dir=default_cache_dir(), backend=get_backend(backend_name))
