from __future__ import annotations

import base64

from fastapi.testclient import TestClient


def _find_message_with_attachment(client: TestClient) -> tuple[str, str]:
    search = client.get(
        "/gmail/v1/users/me/messages",
        params={"q": "has:attachment", "maxResults": 1},
    )
    messages = search.json()["messages"]
    assert messages, "fixture DB should contain at least one message with an attachment"
    message_id = messages[0]["id"]
    full = client.get(f"/gmail/v1/users/me/messages/{message_id}").json()
    attachment_part = next(
        p for p in full["payload"]["parts"] if "attachmentId" in p.get("body", {})
    )
    return message_id, attachment_part["body"]["attachmentId"]


_MAGIC_BYTES_BY_MIMETYPE = {
    "application/pdf": b"%PDF-",
    # docx/xlsx are both zip containers (OOXML) — same magic bytes.
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": b"PK",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": b"PK",
}


def test_get_attachment(client: TestClient) -> None:
    message_id, attachment_id = _find_message_with_attachment(client)
    resp = client.get(f"/gmail/v1/users/me/messages/{message_id}/attachments/{attachment_id}")
    assert resp.status_code == 200
    body = resp.json()
    assert body["attachmentId"] == attachment_id
    assert base64.urlsafe_b64decode(body["data"].encode("ascii"))


def test_get_attachment_is_real_generated_content_not_filler(client: TestClient) -> None:
    """Ticket 0008: attachments carry real pdf/docx/xlsx bytes generated by
    mock_gmail_api.docgen, not synthetic `MOCKATTACHMENTDATA` filler."""
    message_id, attachment_id = _find_message_with_attachment(client)
    full = client.get(f"/gmail/v1/users/me/messages/{message_id}").json()
    attachment_part = next(
        p for p in full["payload"]["parts"] if p["body"].get("attachmentId") == attachment_id
    )
    mimetype = attachment_part["mimeType"]

    resp = client.get(f"/gmail/v1/users/me/messages/{message_id}/attachments/{attachment_id}")
    raw = base64.urlsafe_b64decode(resp.json()["data"].encode("ascii"))

    assert b"MOCKATTACHMENTDATA" not in raw
    assert raw.startswith(_MAGIC_BYTES_BY_MIMETYPE[mimetype])


def test_get_attachment_404(client: TestClient) -> None:
    resp = client.get("/gmail/v1/users/me/messages/msg_x/attachments/att_does_not_exist")
    assert resp.status_code == 404
