"""Typed views over the SQLite rows. Field names are plain/flat here —
translation into Gmail-API-shaped JSON happens in gmail_json.py, not here.

Single-inbox scope: unlike mock-superhuman-mcp's multi-mailbox model, there
is no `Mailbox` dataclass — every row belongs to the one `users/me` inbox,
matching real Gmail's per-account API surface.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class Thread:
    id: str
    subject: str
    label_ids: list[str] = field(default_factory=list)
    history_id: int = 0


@dataclass(frozen=True, slots=True)
class PitchMeta:
    company_name: str
    sector: str
    ask: str
    stage: str


@dataclass(frozen=True, slots=True)
class Message:
    id: str
    thread_id: str
    from_addr: str
    to_addrs: list[str]
    subject: str
    body_text: str
    body_html: str | None
    headers: dict[str, str]
    internal_date: int
    label_ids: list[str]
    history_id: int = 0
    pitch_meta: PitchMeta | None = None


@dataclass(frozen=True, slots=True)
class Attachment:
    id: str
    message_id: str
    filename: str
    mimetype: str
    size_bytes: int
    page_count: int | None
    # Key into the docgen cache (see mock_gmail_api.docgen) that this
    # attachment's real generated bytes are stored under. None for
    # attachments with no generated content (falls back to filler bytes).
    content_ref: str | None = None


@dataclass(frozen=True, slots=True)
class Draft:
    id: str
    message_id: str
    thread_id: str
    created_at: int
